name: CI

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
          - system: aarch64-darwin
            runner: macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v16
      with:
        name: stackptr
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Build development environment
      run: |
        nix develop --system ${{ matrix.system }}
